version: '3'
services:
  modifiers:
    build: .
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - modifiers

  modifiers-mongo:
    image: mongo:3.7
    restart: always
    networks:
      - modifiers
    volumes:
      - /srv/www/modifiers:/data/db

networks:
  modifiers:
    driver: bridge